/* Generated by scripts/generate-tokens.mjs. Do not edit directly. */
export const motionDurationSeconds = {
  "instant": 0,
  "micro": 0.12,
  "fast": 0.18,
  "standard": 0.26,
  "deliberate": 0.38,
  "slow": 0.52,
  "ceremonial": 0.7
} as const;

export const motionEase = {
  "linear": "none",
  "enter": "power3.out",
  "exit": "power2.in",
  "move": "power2.inOut",
  "emphasised": "power4.out"
} as const;

export const motionDistancePixels = {
  "revealDesktop": 20,
  "revealTablet": 16,
  "revealMobile": 10,
  "parallaxDesktopMaximum": 24,
  "parallaxTabletMaximum": 12
} as const;

export const motionStaggerSeconds = {
  "interface": 0.04,
  "cards": 0.06,
  "heading": 0.08,
  "mobile": 0.04
} as const;

export const motionScale = {
  "iconHoverMaximum": 1.02,
  "galleryHoverMaximum": 1.025,
  "imageMaskMaximum": 1.03
} as const;
